export const FETCH_DEVICE = "FETCH_DEVICE";
export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_CAMPAIGN_INFOR = "FETCH_CAMPAIGN_INFOR";
export const FETCH_IP_ADDRESS = "FETCH_IP_ADDRESS";
export const FETCH_SESSION = "FETCH_SESSION";
